export const PLACEHOLDER = '输入消息...'
export const SEND = '发送'
export const LOADING = '加载中...'
export const NEW_CHAT = '新对话'
export const DELETE = '删除'
export const EMPTY_CONVERSATIONS = '暂无对话'
export const EMPTY_CHAT = '选择或创建对话开始聊天'
export const ERROR_NETWORK = '网络错误，请重试'
